feat: add users-api
TyuMeb/Front pull request #24
Opened 2023-08-12 23:34 UTC by andpigge

2023-08-26 13:56 UTC, Resaw-git reviewed
`headers: {Authorization: 'JWT ${getCookie("accessToken")}'}` везде повторяется, вынеси в константу и переиспользуй. Создавать отдельный редьюсер для квери параметров не очень хорошо, возможно есть более просто решение.

2023-08-26 13:56 UTC, Resaw-git commented on src/redux/slices/query-params-slice.ts
Напомни пожалуйста, зачем нам хранить квери параметры в сторе?

2023-08-26 13:56 UTC, Resaw-git commented on src/redux/api/api-slice.ts
> +    tagTypes: ["Users"],
Это нам пока не нужно

2023-08-26 13:56 UTC, Resaw-git commented on src/redux/api/users-api-slice.ts
> +            providesTags: ["Users"],
и это

2023-08-26 18:47 UTC, andpigge commented on src/redux/slices/query-params-slice.ts
Чтобы получить доступ к квери параметрам страницы сброса пароля.
После их использовать в модалке, чтобы послать запрос на сервер с токеном и uid.

2023-08-26 18:49 UTC, andpigge commented on src/redux/slices/query-params-slice.ts
getCookie("accessToken") не получилось вынести в константу.
Падает vercel с ошибкой, что не может компилировать страницы.

2023-08-26 18:52 UTC, andpigge commented on src/redux/slices/query-params-slice.ts
Создавать отдельный редьюсер для квери параметров не очень хорошо, возможно есть более просто решение.

Мы не имеем доступ к модалке на странице, чтобы перебросить квери. Модалка подключается в шаблоне.
Поэтому я не знаю другого решения.

2023-08-27 18:25 UTC, andpigge commented on src/redux/slices/query-params-slice.ts
headers: {Authorization: 'JWT ${getCookie("accessToken")}'} везде повторяется, вынеси в константу и переиспользуй.

Перенес:
const headers = {
    Authorization: `JWT ${getCookie("accessToken")}`,
};

Ошибка:
error node_modules\typescript-cookie\dist\typescript-cookie.mjs (45:0) @ get
- error ReferenceError: document is not defined

2023-10-24 06:00 UTC, Resaw-git requested changes
1. Необходимо добавить .env.development для dev разработки
2. Для вывода сообщений об ошибках необходимо использовать интерфейс инпута
3. После успешного сброса пароля необходимо уведомить пользователя перейти на почту чтобы задать новый пароль
4. После успешного ввода нового пароля так же необходимо уведомить пользователя об успешном завершении
5. Для фона модального окна нового пароля необходимо добавить иллюстрацию, аналогичную сбросу пароля
*6. Добавить ко всем асинхронным операциям индикатор загрузки

2023-10-27 15:20 UTC, merged