feat/ added registration
TyuMeb/Front pull request #25
Opened 2023-08-13 20:30 UTC by krekser37

Добавила возможность регистрации

2023-08-13 20:52 UTC, andpigge reviewed
Я почти уверен, что для подтверждения регистрация другой эндпоинт.
POST /auth/users/activation/

Сейчас у нас:
/activate${uid}/${token}/
в функции verifyEmail.

Я точно не помню. Но у меня уже пишет 429(. Сегодня посмотреть не смогу.
Смогу через 16 часов

2023-08-13 20:52 UTC, andpigge commented on src/redux/slices/modal-slice.ts
> +    typeModal: "registration",
Привет. Это не нужно менять.

2023-08-13 20:52 UTC, andpigge commented on src/redux/marketplace-api/authorization-api.ts
> +            }) => ({
можно вынести в interface:
interface IRegister {
    email: string;
    ...
}

2023-08-26 14:11 UTC, Resaw-git requested changes
Нужно будет созвониться и протестировать регистрацию, у меня не получилось её пройти

2023-11-03 15:43 UTC, merged