Feat/storybook
TyuMeb/Front pull request #31
Opened 2023-08-26 16:54 UTC by andpigge

Общая ветка для задачи UI

2023-08-26 16:57 UTC, andpigge commented
Переношу комментарии Гены.

2023-08-26 16:58 UTC, andpigge commented
**Гена писал** для задачи по input:

Валидацию в инпутах делать не надо было (maxLength, minLength), нужен пропс с состоянием ошибки и текстом ошибки. Те пропсы которые ты не меняешь нужно передать как остаточные параметры (onFocus, onBlur). Так же необходимо реализовать 2х стороннее связывание. Хотелось бы к каждому компоненту видеть документацию как в примере. Директорию с примерами можно удалить. Ветку необходимо было создать одну на всех (пример feat/storybook).

2023-08-26 16:59 UTC, andpigge commented
> 

1) нужен пропс с состоянием ошибки и текстом. Он ведь уже есть. Текст ошибки это helperText, error - это есть ошибка или нет. Какие вместо этого нужны пропсы?
2) так же необходимо реализовать 2х стороннее связывание. С кем мне этот input связать? Или ты имеешь ввиду для storybook это сделать?

2023-08-26 17:00 UTC, andpigge commented
> **Гена писал** для задачи по input:
> 
> Валидацию в инпутах делать не надо было (maxLength, minLength), нужен пропс с состоянием ошибки и текстом ошибки. Те пропсы которые ты не меняешь нужно передать как остаточные параметры (onFocus, onBlur). Так же необходимо реализовать 2х стороннее связывание. Хотелось бы к каждому компоненту видеть документацию как в примере. Директорию с примерами можно удалить. Ветку необходимо было создать одну на всех (пример feat/storybook).

1) нужен пропс с состоянием ошибки и текстом. Он ведь уже есть. Текст ошибки это helperText, error - это есть ошибка или нет. Какие вместо этого нужны пропсы?
2) так же необходимо реализовать 2х стороннее связывание. С кем мне этот input связать? Или ты имеешь ввиду для storybook это сделать?

2023-08-26 17:00 UTC, andpigge commented
Гена писал для задачи по button:

Менять компоненты по проекту не нужно было, достаточно только написать библиотечные. Если мы передаём значение в компонент как child то тип у него будет ReactNode (пример: props {children: ReactNode} <Button>{children}</Button>). Хотелось бы видеть документацию к компоненту как в примере. Неверное название ветки. Ветку нужно было создать одну на всех (например feat/storybook).

2023-10-04 07:50 UTC, MariaGrom commented on src/components/modals/registration/registration.tsx
> +                    }>
Может быть под эти кнопки с отправкой тоже стоит добавить ui компонент, если созданный Button не подходит?

2023-10-04 07:50 UTC, MariaGrom commented on src/components/modals/reset-password-confirm/reset-password-confirm.tsx
> +                            }>
и здесь тоже тот же типа кнопки

2023-10-04 07:50 UTC, MariaGrom commented on src/components/modals/reset-password/reset-password.tsx
> +                            }>
и здесь

2023-10-04 07:50 UTC, MariaGrom commented on src/components/modals/signin/signin.tsx
> +                    <div style={{ width: "296px" }}>
инлайновые стили вроде как не очень хорошая практика

2023-10-04 07:50 UTC, MariaGrom commented on src/components/modals/signin/signin.tsx
> +                    }>
еще одна кнопка на отправку

2023-10-04 07:50 UTC, MariaGrom commented on src/components/modals/validation.ts
> +        onChange(`Длина ${field} не может быть больше ${length} символов!`);
этот чек нужно будет доработать, так как 12 символов - довольно странное число для ограничения длины почты или фамилии. не совсем дружелюбно.
Плюс такие значения (как их любят называть - мифические) рекомендуют выносить в константы для удобства замены при необходимости.

2023-10-04 07:54 UTC, MariaGrom commented on src/components/modals/reset-password-confirm/reset-password-confirm.tsx
> +                            className={cx("text", "button")}
и здесь тоже тот же типа кнопки

2023-10-04 15:13 UTC, andpigge commented on src/components/modals/validation.ts
> +        onChange(`Длина ${field} не может быть больше ${length} символов!`);
Эта задача все же для ui компонентов. Задача по валидации, будет отдельной.

2023-10-04 15:14 UTC, andpigge commented on src/components/modals/registration/registration.tsx
> +                    type="submit"
Верно. Мы обсуждали с Катей. Наверное добавлю уже сейчас.

2023-10-04 16:53 UTC, MariaGrom commented on src/components/modals/validation.ts
> +        onChange(`Длина ${field} не может быть больше ${length} символов!`);
окей.
Задачка и так получилась очень объемной. Такие сложновато проверять на самом деле.

2023-10-21 09:18 UTC, Resaw-git requested changes
1. Default Input не меняет своего состояния на disabled и error, остаётся возможность ввода и не меняются стили для error
2. Phone Input нельзя ввести значение в сторибуке напрямую, не через value
3. Расхождения в вёрстке, скрины отправлю в тг

2023-10-21 09:18 UTC, Resaw-git commented on src/hooks/use-Input.ts
use-Input.ts -> use-input.ts

2023-10-21 12:20 UTC, merged